#!/bin/bash
ADDR=...

SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# get the working dir to send
WORK_NAME=${PWD#"/Users/nmhkahn/Works/"}
IFS="/" read -ra WORK_NAME <<< "$WORK_NAME"
WORK_DIR="/Users/nmhkahn/Works/"$WORK_NAME

echo Sending to server ${ADDR}...

if [ "$1" == "all" ] ; then
    rsync -avrhc \
        --exclude "*.git" --exclude "*.swp" --exclude "*.DS_Store" \
        -e 'ssh -p 30101' \
        $WORK_DIR \
        root@${ADDR}:/root/works/
else
    rsync -avrhc \
        --exclude-from "/Users/user/Works/.bin/.ignore_ext" \
        --exclude "*.git" --exclude "*.swp" --exclude "*.DS_Store" \
        -e 'ssh -p 30101' \
        $WORK_DIR \
        root@${ADDR}:/root/works/
fi
